sequenceDiagram
    participant Bob
    participant LoanAggregatorSmartContract
    participant Alice
    participant PWN
    participant AAVE
    participant CollatoralisationStation
    participant OlasDonationManagerContract
    participant UniswapV2Pools
    participant ChainlinkOracle

    Bob ->> LoanAggregatorSmartContract: Deposit DAI for loans
    Charlie ->> AAVE: Deposit OLAS for loans
    AAVE ->> Charlie: aOLAS
    Alice ->> PWN: Loan Request
    PWN ->> CollatoralisationStation: Poll Loan Requests
    CollatoralisationStation ->> LoanAggregatorSmartContract: Check Available Funds for loan
    CollatoralisationStation ->> OlasDonationManagerContract: Check Nft Claimable OLAS
    CollatoralisationStation ->> UniswapV2Pools: Get OLAS Weth price
    CollatoralisationStation ->> ChainlinkOracle: Get Weth USD Price
    CollatoralisationStation ->> CollatoralisationStation: Analyze Data
    CollatoralisationStation ->> PWN: Create Loan Offer
    Alice ->> PWN: Accept Offer
    Alice ->> PWN: TX NFT

    LoanAggregatorSmartContract ->> AAVE: Borrow OLAS
    AAVE ->> LoanAggregatorSmartContract: OLAS
    CollatoralisationStation ->> LoanAggregatorSmartContract: TX Loan To fulfill PWN
    LoanAggregatorSmartContract ->> PWN: OLAS
    PWN ->> Alice: GIB Loan
    Alice ->> PWN: Repays Loan
    PWN ->> LoanAggregatorSmartContract: Settle Loan + Fees
    LoanAggregatorSmartContract ->> Bob: Collect DAI + Fees
    Alice ->> PWN: REFUSE TO Pay
    PWN ->>LoanAggregatorSmartContract: txs Alice's nft
    CollatoralisationStation ->> LoanAggregatorSmartContract: proxy call to multisig
    LoanAggregatorSmartContract ->> OlasDonationManagerContract: claim OLAS
    CollatoralisationStation ->> LoanAggregatorSmartContract: Liquidate enough to repay Bob (Keeps the rest as OLAS)
    CollatoralisationStation ->> AAVE: OLAS
    AAVE ->> Charlie: OLAS + fees
    LoanAggregatorSmartContract ->> Bob: Collect DAI + Fees
    LoanAggregatorSmartContract ->> CollatoralisationStation: Collect